//
//  HealthInfoController.swift
//  know.
//
//  Created by Madison Kaori Shino on 8/23/19.
//  Copyright © 2019 Darin Armstrong. All rights reserved.
//

import Foundation

class  HealthInfoController {
    
    static let shared = HealthInfoController()
    
    //Info Categories
    var infoCategories: [HealthInfo] = []
    
    //Health Info Data
    let fertility = HealthInfo(subject: "Fertility",
                               firstSecTitle: "Fertile Window",
                               firstSecBody: "The fertile window is the time in each cycle when it’s possible to become pregnant. It includes the five days leading up to ovulation (when estrogen rises sharply) and the 24 hours ovulation occurs (1).\n\nThe fertile window displayed in the app is just an estimate. In reality, your true fertile window may occur earlier or later in your cycle. The position of your fertile window can also change cycle-to-cycle. To find out when your fertile window occurs each cycle, you’ll need to take ovulation tests, or track your basal body temperature and certival fluid.\n\nThe fertile window estimate in this app is not meant to be used as birth control. You can choose not to display the fertile window. This option is available under the Settings in the menu.",
                               secSecTitle: "What's Happening",
                               secSecBody: "It’s a common misconception that you can only become pregnant on the day you ovulate, or that you can become pregnant at any time in the cycle. Neither of these are true.\n\nOvulation occurs when one of your ovaries release an egg. This egg can be fertilized for up to 24 hours as it journeys through the fallopian tube towards the uterus. (2)\n\nSperm can live inside your body for up to five days (1-3). This means if sperm enters your reproductive tract for up to five days before ovulation, it may fertilize the egg, leading to pregnancy. If the egg is not fertilized withing 12-24 hours of ovulation, it disintegrates and passes out of your uterus with your period.\n\nThe length of the fertile window is defined by the qualities of your cervical fluid and the health of the sperm (2). While the fertile window lasts about six days, the greatest chance of conception is in the two days before ovulation and the day of ovulation. These odds quickly decrease the day after ovulation (1,3).",
                               thirdSecTitle: "What’s considered normal and healthy",
                               thirdSecBody: "-  A fertile window of ~6 days\n-  A fertile window that can happen at a different time each cycle, even in people who consider their cycles regular.\n\nThe timing of your fertile window depends on when you ovulate in each cycle. This changes in response to factors life stress, diet, sleep, environment, partying, and travel. It also changes a lot in the years after your menstrual cycle begins, after pregnancy, and leading up to menopause. In between those times, some people have a regular cycle, but most people don’t.",
                               fourthSecTitle: "Indicators",
                               fourthSecBody: "The timing of the fertile window can be estimated by these primary signs of fertility.\n\n-  Changes in cervical fluid: fluid goes from dry to creamy to an egg white-like substance on your most fertile days around your ovulation day.\n\n-  Basal body temperature (BBT): BBT is your body’s temperature at rest. Slight variations in BBT can be used to determine when ovulation has occured.\n\n-  Luteinizing hormone (LH): This hormone triggers ovulation and can be detected by at-home ovulation kits. Keeping a record of your LH peak can help you better predict your next fertile window. (5,6)\n\nObserving the changes in one or more of these signs can help you determine the timing of your fertile window. They are the signs used in most Fertility Awareness Methods of contraception. Some methods include other optional signs or fertility, including cervical position (7).\n\nTo know when your actual fertile window happened in any given cycle, you have to determine when you’ve ovulated. Tracking ovulation at home requires taking your BBT each morning or ovulation urine tests (though neither methods are perfectly accurate). Becuase ovulation can change cycle-to-cycle, you have to do this on a continual basis. But still, these tools only show when ovulation has happened in the past (like with BBT), or when it may be just about to happen (like ovulation tests). That only covers 1-2 days of your fertile window. They don’t predict when ovulation will happen in the future, or when you’ve entered into the beginning of your fertile window.\n\nThe best at-home method for estimating a current fertile window and predicting an upcoming ovulation is by monitoring cervical fluid (5). Monitoring fluid consistency is a key part of some fertility awareness methods.",
                               fifthSecTitle: "Medical Terminology",
                               fifthSecBody: "Luteinizing Hormone (LH): This hormone triggers ovulation and can be detected by at home ovulation predictor kits.\n\nNovum: the reproductive cell, or “egg”, formed in the ovaries, and released into the fallopian tubes.\n\nSperm: the reproductive cell formed in the testes.\n\nFollicular Phase: the first phase of your cycle that includes the first day of your period up to ovulation.\n\nLuteal Phase: the second phase of your cycle, from ovulation to the day before your next period.\n\n\n Fertility Awareness Method (FAM)L FAMs are based on observing and tracking scientifically evidenced fertility indicators to determine your fertility each day. They are used for becoming pregnant, natural birth control, evaluating gynecological problems, and understanding the body. Not to be confused with the Rhythm Method.",
                               sixSecTitle: "Your body is not a clock",
                               sixSecBody: "Every body is different. Variations in your cycle are normal and healthy. Comparing your cycle to global averages can create an impression there’s something wrong, when everything is probably OK. It’s best to talk to your doctor when you notice something that’s unusual for you personally, or to better understand why aspects of your cycle may fail outside the ranges set by global statistics.",
                               sevenSecTitle: "References",
                               sevenSecBody: "1. Wilcox AJ. Timing of sexual intercourse in relation to ovulation. Effects on the probability of conception, curvival of the pregnancy, and sex of the baby. New England Journal of Medicine. 1995.\n\n2. Suarex SS, Pacey AA. Sperm transport in the female reproductive tract. Human Reproduction Update. 2006\n\n3. Dunson DB et al. Day-specific probabilites of clinical pregnancy based on two studies with imperfect measures of ovulation. Human Reproduction. 1999. 14(7):1835-1839\n\n4. Collins, WP. Biochemical indices of potential fertility. International Journal of Gynecology and Obstetrics, Supplemental, 1, pp. 35-44, 1989.\n\n5. Fehring RJ, Schneider M, Raviele K. Variability in the phases of the menstural cycle. Journal of Obstetrics, Gynecologic, and Neonatal Nursing. 2006 May-Jun; 25 (3):376-84.\n\n6. Lenton EA, Landgren BM, Sexton L. Normal variation in the length of the luteal phase of the menstrual cycle: identification of the short luteal phase. British Journal of Obstetrics and Gynecology. 1984. 91 (7):685-9.\n\n7. Weschler, Toni. Taking charge of your fertility (10 Edition). 2006. New York: Collins.\n\n8. Wilcox AJ. The timing of the “fertile window” in the menstrual cycle: day specific estimates from a perspective study. British Medical Journal. 2000; 321:1259.\n\n9.Jukic AM (2007). Life-style and reproductive factors associated with follicular phase length. Journal of Women’s Health. November; 16(9): 1340-1347.\n\n10. Pallone SR and Bergus GR (2009). Fertility awareness-based methods: Another other for familty planning. Journal of the American board of family medicone. March-April. Vol 22. No. 2:147-157.",
                               eightSecTitle: nil,
                               eightSecBody: nil,
                               nineSecTitle: nil,
                               nineSecBody: nil)
    
    let periods = HealthInfo(subject: "Periods",
                             firstSecTitle: "Periods",
                             firstSecBody: "Your monthly bleeding. The first day of the period is usually a sign that you are not pregnant.",
                             secSecTitle: "What's Happening",
                             secSecBody: "Your egg hasn’t been fertilized and/or attached itself to the uterine wall. Your uterus then begins shedding to lining that grew to recieve a fertilized egg. Contractions help break down and release the lining of the uterus. These contractions are the cause of cramps some people get with their period. (1).",
                             thirdSecTitle: "What’s considered normal and healthy",
                             thirdSecBody: "-  Duration between 4 to 7 days./n-  Bleeding between 10-80 mL or 1 to 6 tablespoons of fluid./n-  Heaviest bleeding on the first and second day. (3-4)\n\nSome people see clots or clumps in their flow, especially on their heaviest days (2). Volume wise, the entire flow can vary from 10-80 mL or about 1 to 6 tablespoons (3-4). Consider those numbers in more everyday use terms:\n\n-  One soaked regular tampon or pad holds about 5 mL. (2)\n-  One soaked maxi tampon or pad holds about 10 mL. (2)\n-  Depending on size and brand, one full menstrual cup holds 15-30 mL (most have a couple volume markers on the inside of the cup too)\n\nA heavy day for you might mean using two tampons, but a heavy for someone else might mean using five. Any of this may be normal for you, and keep in mind that these numbers are just a guide to help you understand the broad ranges of whay may be considered normal.",
                             fourthSecTitle: "Indicators",
                             fourthSecBody: "-  Bleeding\n-  Cramps and pains\n-  PMS (premenstrual symptoms) symptoms may extend a few days into the period",
                             fifthSecTitle: "Relief",
                             fifthSecBody: "-  Hot waterbottles or compresses.\n-  Therapeutic heat patches that are designed to deliver thermal heat (not spicy surface heat) can offer non-pharmaceutical but discreet relief when not at home.\n-  Reduced caffeine intake.\n-  Over-the-counter pain medication.",
                             sixSecTitle: "Medical Terminology",
                             sixSecBody: "Menstrual Period - Another name for ‘the period’, it may also be called menstrual bleeding, menses, catamenia.\n\nEndometrium -The lining of the uterus which grows each cycle in preperation to receive a fertilized egg and, in the absense of pregnancy, is then shed during the period.\n\nDysmenorrhea - Pain with the period, describes the cramps many people get with their period.\n\nProstaglandins - Substances the body naturally makes involved in inflammation and pain, believed to be the cause of cramps with the period.",
                             sevenSecTitle: "You should see a doctor when…",
                             sevenSecBody: "You bleed through regular strength tampons or pads in one hour for more than two-consecutive hours, or if you’re regularly bleeding for more than 7 days.",
                             eightSecTitle: "Your body is not a clock",
                             eightSecBody: "Every body is different. Variations in your cycle are normal and healthy. Comparing your cycle to global averages can create an impression there’s something wrong, when everything is probably OK. It’s best to talk to your doctor when you notice something that’s unusual for you personally, or to better understand why aspects of your cycle may fail outside the ranges set by global statistics.",
                             nineSecTitle: "References",
                             nineSecBody: "1. Durain D (2004). Primary dysmenorrhea: assessment and management update. Journal of Midwifery and Women’s Health. 49:520-528.\n\n2. Prior JC. For Healthcare Providers: Managing Menorrhagia Without Surgery. Center for Menstrual Cycle and Ovulation Reasearch. Last Update December 6, 2007.\n\n3. Dasharathy SS et al. Menstrual bleeding patterns among regularly menstruating women. American Journal of Epidemiology. 2012 March 15; 175 (6): 536-45\n\n4. Warner PE, Critchley HO. Menorrhagia I: measured blood loss, clinical features and outcomes in women with heavy periods: a survey with follow-up data. American Journal of Obstetrics and Gynecology. 2004 190:1216-1223.")
    
    let PMS = HealthInfo(subject: "PMS",
                         firstSecTitle: "PMS",
                         firstSecBody: "Premenstrual syndrome (PMS) is a recurring pattern of emotional, physical, and behavioral changes in the days before your period.",
                         secSecTitle: "What’s considered normal and healthy",
                         secSecBody: "Up to 80% of people say they experience one or more premenstrual symptoms and 20-32% of people say their symptoms are so significant that PMS affects their daily lives (1). Despite being so commonplace, the medical community is in disagreement about the exact cause of PMS.\n\nEach Individual’s experience of PMS is unique in intensity, length and variety of symptoms (2). If you experience PMS to any degree, the timing and collection of your symptoms will stay about the same, but may vary in intensity each cycle (3-5). Things like diet, caffeine, stress, increasing age, and depression can increase the intensity of your symptoms (4).",
                         thirdSecTitle: "Indicators",
                         thirdSecBody: "Over 150 symptoms have been atributed to PMS. Some common symptoms are:\n\n-  Headaches and migranes\n-  Bloating, water retention, and weight gain\n-  Nausea and constipation\n-  Anxiety, tearfulness, agitation or emotional sensitivity\n-  Trouble sleeping, acne, and food cravings (6)",
                         fourthSecTitle: "Relief",
                         fourthSecBody: "There are many ways to manage premenstrual symptoms, but finding the most effective practices for alleviating PMS takes individual exploration. Clue users have suggested some of the following:\n\n-  Reducing or eliminating caffeine intake\n-  Over the counter pain medication, such as ibuprofen\n-  Hot water bottles, hot compresses, or heating pads for pain.\n-  Rest",
                         fifthSecTitle: "Medical terminology",
                         fifthSecBody: "Premenstrual syndrome (PMS) - recurring pattern of emotional, physical, and behavioral changes in the days before your period that may be significant enough to disprupt daily life.",
                         sixSecTitle: "You should see a doctor if…",
                         sixSecBody: "The emotional or physical symptoms of PMS are beyond your ability to manage, and they negatively affect your relationships with others or your personal well-being.",
                         sevenSecTitle: "Your body is not a clock",
                         sevenSecBody: "Every body is different. Variations in your cycle are normal and healthy. Comparing your cycle to global averages can create an impression there’s something wrong, when everything is probably OK. It’s best to talk to your doctor when you notice something that’s unusual for you personally, or to better understand why aspects of your cycle may fall outside the ranges set by global statistics.",
                         eightSecTitle: "References",
                         eightSecBody: "1.  Biggs WS. Premenstrual Syndrome and Premenstrual Dysphric Disorder American Family Physician. 2011.\n\n2. Vliet Elizabeth. Screaming to be Heard: Hormonal Connections Women Suspect and Doctors Still Ignore. Revised Eidtion. 2001. Frist Rowan & Littlefield.\n\n3. Allen LM, Lam AC. Premenstrual syndrome and dysmoenorrhea in adolscenets. Adolescent Medicine: State of the Art Reviews. 2012 Apr; 23(1):139-63\n\n4. Dickerson LM, Mazyck PJ, Hunter MH. Premenstrual Syndrome. American Family Physician. 2003 April 15;67(8):1743-1752\n\n5. Braverman PK. Premenstrual syndrome and premenstrual dysphoric disorder. Journal of Pediatric and Adolescent Gynecology. 2007 Feburary. Volume 20, Issue 1, pages 3-12.\n\n6. Durain D Primary dysmenorrhea: assessment and management update. Journal of Midwiferey and Women’s Health. 2004; 49:520-528.",
                         nineSecTitle: nil,
                         nineSecBody: nil)
    
    func loadHealthInfo() {
        infoCategories = [fertility, periods, PMS]
    }
}
